services:
  - type: web
    name: aplicacion-django
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn aplicaci-on.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: aplicaci-on.settings
