# Generated by Django 5.2.7 on 2025-10-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='summary',
            field=models.TextField(default='Sin resumen'),
            preserve_default=False,
        ),
    ]
